name: CI

on:
  pull_request:
  push:
    branches: [main, staging, dev]

jobs:
  node-ci:
    uses: Guard-AI-ESP/guard-ai-devx/.github/workflows/node-ci.yml@main
    with:
      node-version: "20"
      working-directory: "./svelte-guardai"
      run-tests: false
      build: true
